fix occurences typo in README.md
sensu-plugins/sensu-plugins-graphite pull request #42
Opened 2016-09-26 16:37 UTC by yanc0

## Purpose

Fix typo in README.md

2016-09-26 23:57 UTC, eheydrick requested changes

2016-09-26 23:57 UTC, eheydrick commented on README.md
> + * bin/handler-graphite-occurences
should be 2 r's in occurrences.

2016-09-27 07:08 UTC, yanc0 commented on README.md
> + * bin/handler-graphite-occurences
@eheydrick Thanks ;)

2016-09-27 16:54 UTC, eheydrick approved these changes

2016-09-27 16:54 UTC, merged

2016-09-27 16:54 UTC, eheydrick commented
Thanks!