Remove short since it's duplicate...
sensu-plugins/sensu-plugins-graphite pull request #53
Opened 2017-06-12 02:08 UTC by ROunofF

## Pull Request Checklist

Reference : #50

#### General

- [X] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [X] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [X] RuboCop passes

- [X] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatablity Issues

2017-06-12 16:37 UTC, majormoses requested changes
Overall looks good, just a bit more clear changelog messages should be given when breaking changes are done.

2017-06-12 16:37 UTC, majormoses commented on CHANGELOG.md
> +- Remove short options -s on hostname_sub, it was already taken
Lets put this under a section with `### Breaking Changes` to be nice and loud about this. Also lets indicate which checks this affects.

2017-06-14 01:39 UTC, ROunofF commented on CHANGELOG.md
> +- Remove short options -s on hostname_sub, it was already taken
Hmmm the -s for host_sub was simply not usable... Unless I'm missing something?

Output when adding a puts config in options.rb:
`$ check-graphite-data.rb -s localhost -t test
{:name=>"graphite check", :from=>"-10mins", :until=>"now", :allowed_graphite_age=>60, :server=>"localhost", :target=>"test"}
CheckGraphiteData OK: graphite check value OK
`

2017-06-14 01:48 UTC, majormoses commented on CHANGELOG.md
> +- Remove short options -s on hostname_sub, it was already taken
fair enough, put it under a `### Fixed` then.

2017-06-14 01:48 UTC, majormoses commented on CHANGELOG.md
> +- Remove short options -s on hostname_sub, it was already taken
also include the affected checks.

2017-06-14 02:35 UTC, majormoses approved these changes

2017-06-14 02:35 UTC, merged

2017-06-14 02:49 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-graphite/versions/2.2.1